name: fofin
channels:
  - conda-forge
  - ibmdecisionoptimization
  - anaconda
dependencies:
  - python = 3.6
  - pip >= 19.0
  - numpy = 1.15.4
  - COMPAS = 0.7.1
  - multiprocess
  - ecos >= 2
  - scs >= 1.1.3
  - cplex
  - cvxopt
  - pip:
    - git+https://github.com/BlockResearchGroup/compas_fofin.git#egg=compas_fofin
    - cvxpy
